---
# Source: eks-nvme-ssd-provisioner/templates/daemonset.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  namespace: kube-system
  name: eks-nvme-ssd-provisioner
  labels:
    helm.sh/chart: eks-nvme-ssd-provisioner-0.1.1
    app.kubernetes.io/name: eks-nvme-ssd-provisioner
    app.kubernetes.io/instance: eks-nvme-ssd-provisioner
    app.kubernetes.io/version: "1.0.1"
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: eks-nvme-ssd-provisioner
      app.kubernetes.io/instance: eks-nvme-ssd-provisioner
  template:
    metadata:
      labels:
        app.kubernetes.io/name: eks-nvme-ssd-provisioner
        app.kubernetes.io/instance: eks-nvme-ssd-provisioner
    spec:
      automountServiceAccountToken: false
      nodeSelector:
        aws.amazon.com/eks-local-ssd: "true"
      priorityClassName: system-node-critical
      containers:
      - name: eks-nvme-ssd-provisioner
        image: ghcr.io/zenaptix-lab/eks-nvme-ssd-provisioner:1.0.1
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        volumeMounts:
          - mountPath: /pv-disks
            name: pv-disks
            mountPropagation: "Bidirectional"
          - mountPath: /nvme
            name: nvme
            mountPropagation: "Bidirectional"
      volumes:
      - name: pv-disks
        hostPath:
          path: /pv-disks
      - name: nvme
        hostPath:
          path: /nvme
